TradingPlaces/Controllers/RealEstateController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net.Mail;
using TradingPlaces.Classes;
using TradingPlaces.Models;
using TradingPlaces.Helpers;

namespace TradingPlaces.Controllers
{
    public class RealEstateController : Controller
    {   
        readonly RealEstateService _realEstateService;
        readonly EmailService _emailService;
        private int defaulPageSize = 10;

        public RealEstateController()
        {
            RealEstateContext db = DBInitialization.InitializeDB();
            _realEstateService = new RealEstateService(db);
            _emailService = new EmailService(db);
        }

        /// <summary>
        /// GET: /RealEstate/Index - main page with photo gallery
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            var houseList = _realEstateService.GetHousesWithPhotos();
            var items = LinqRandomsExtensions.Randoms(houseList, 12);
            return View(items);
        }

        /// <summary>
        /// GET: /RealEstate/Sale - Sale page with models list
        /// </summary>
        /// <param name="pageSize"></param>
        /// <param name="pageNum"></param>
        /// <returns></returns>
        public ActionResult Sale(int pageSize = 0, int pageNum = 0)
        {
            if (HttpContext.Request.Cookies["pageSize"] != null && pageSize == 0)
            {
                try
                {
                    pageSize = Int32.Parse(HttpContext.Request.Cookies["pageSize"].Value);
                }
                catch (FormatException e)
                {
                    pageSize = 0;
                }
            }
            if (pageSize == 0)
            {
                pageSize = defaulPageSize;
            }
            HttpContext.Response.Cookies["pageSize"].Value = pageSize.ToString();
            ViewData["PageNum"] = pageNum;
            ViewData["ItemsCount"] = _realEstateService.GetHousesCount();
            ViewData["PageSize"] = pageSize;
            var houseList = _realEstateService.GetHousesListInPage(pageSize, pageNum);
            return View(houseList);
        }

        /// <summary>
        /// GET: /RealEstate/Delete/5 - delete house model page 
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpGet]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }
            Construction b = _realEstateService.GetById(id);
            if (b == null)
            {
                return HttpNotFound();
            }
            return View(b);
        }

        /// <summary>
        /// POST: /RealEstate/Delete/5 - delete house model from db 
        /// </summary>
        /// <param name="id"></param>
        /// <param name="collection"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Delete(int? id, FormCollection collection)
        {
            if (id == null)
            {
                return HttpNotFound();
            }
            Construction house = _realEstateService.GetById(id);
            if (house == null)
            {
                return HttpNotFound();
            }
            _realEstateService.DeleteHouse(house);
            return RedirectToAction("Sale");
        }

        /// <summary>
        /// GET: /RealEstate/info/5 - get info page to create/edit house model
        /// </summary>
        /// <param name="id"></param>
        /// <param name="pageNum"></param>
        /// <returns></returns>
        [HttpGet]
        public ActionResult Info(int? id, int pageNum = 0)
        {
            if (id == null)
            {
                Construction newHouse = new Construction();
                return View(newHouse);
            }
            Construction house = _realEstateService.GetById(id);
            if (house == null)
            {
                return HttpNotFound();
            }
            _realEstateService.SetStringImage(house);
            
            HttpContext.Response.Cookies["pageNum"].Value = pageNum.ToString();
            return View(house);
        }

        /// <summary>
        /// POST: /RealEstate/info/5 - save house model in db
        /// </summary>
        /// <param name="house"></param>
        /// <param name="uploadImage"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Info(Construction house, HttpPostedFileBase uploadImage)
        {
            if (ModelState.IsValid)
            {
                byte[] imageData = null;
                if (uploadImage != null)
                {
                    using (var binaryReader = new BinaryReader(uploadImage.InputStream))
                    {
                        imageData = binaryReader.ReadBytes(uploadImage.ContentLength);
                        house.Image = imageData;
                    }
                }
                _realEstateService.AddSaveHouse(house);
                int pageNum = 0;
                if (HttpContext.Request.Cookies["pageNum"] != null)
                {
                    try
                    {
                        pageNum = Int32.Parse(HttpContext.Request.Cookies["pageNum"].Value);
                    }
                    catch { }
                }
                return RedirectToAction("Sale", new { pageNum = pageNum });
            }
            return View(house);
        }

        /// <summary>
        /// GET: /RealEstate/Contact - contact page with ours contacts, google map and send-mail form
        /// </summary>
        /// <returns></returns>
        public ActionResult Contact()
        {
            Email newEmail = new Email();
            return View(newEmail);
        }

        /// <summary>
        /// POST: /RealEstate/Contact/ -  save Email model in db and send email
        /// </summary>
        /// <param name="emailModel"></param>
        /// <returns></returns>
        [HttpPost, ActionName("Contact")]
        public ActionResult SendEmail(Email emailModel)
        {
            if (ModelState.IsValid)
            {
                _emailService.AddEmail(emailModel);
                bool result = SendingEmail.SendEmail(emailModel);
                if (result)
                {
                    ViewBag.Message = "Your message has been sent successfully!";
                }
                else
                {
                    ViewBag.Message = "Error sending message :(";
                }
                return View("SendEmail");
            }
            return View("Contact", emailModel);
        }

    }
}

TradingPlaces/Views/RealEstate/Contact.cshtml
@using TradingPlaces.Helpers
@model TradingPlaces.Models.Email
@{
    ViewBag.Title = "Contact";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link rel="stylesheet" href="@Url.Content("~/Content/css/frontend.css")">

<style type="text/css">
    #Title {
        position:absolute;
        width:165px;
        width:180px\9;
        #width:180px;
        height:20px; 
        height:20px\9;
        #height:18px;
    }
</style>

@section scripts
{
    <script type="text/javascript">
        window.onload = function () {
            var myLatlng = new google.maps.LatLng(51.5684959, 0.0091416);

            var myOptions = {
                zoom: 16,
                center: myLatlng,
                mapTypeId: google.maps.MapTypeId.ROADMAP
            }
            var element = document.getElementById("map-canvas");
            var map = new google.maps.Map(element, myOptions, marker);
            var marker = new google.maps.Marker({
                position: myLatlng,
                map: map,
                title: "Trading Places"
            });

        }
        function setBestTime(cb, message) {
            ContactTime = $('#ContactTime').attr('value');
            cb = document.getElementById(cb);
            timeMessage = message + " ";
            if (cb.checked) {
                ContactTime += timeMessage;
            }
            else {
                ContactTime = ContactTime.replace(timeMessage, "");
            }
            $('#ContactTime').val(ContactTime);
        }
    </script>
}

@section MenuCap {
    <ul class="main-nav">
        <li><a href="/RealEstate/">MAIN</a></li>
        <li><a href="/RealEstate/Sale">SALE</a></li>
        <li><a href="/RealEstate/Info">INFO</a></li>
        <li class="active"><a href="/RealEstate/Contact">CONTACT</a></li>
    </ul>
}

@section SideBar {
    <div class="sidebar">
    <div class="border-section">
        <div class="bottom">
            <h3>Find a Property</h3>
            <ul class="vert-nav2">
                <li><a href="#" class="main-btn"><span>To Buy</span></a></li>
                <li><a href="#" class="main-btn"><span>To Rent</span></a></li>
                <li><a href="#" class="main-btn"><span>Register With Us</span></a></li>
            </ul>
        </div>
    </div>
    <div class="left-nav">
        <ul class="vert-nav">
            <li><a href="#">About Us</a></li>
            <li><a href="#">Mortgages</a></li>
            <li><a href="#">Property Lawyers</a></li>
            <li><a href="#">Surveyors</a></li>
            <li><a href="#">Schools</a></li>
            <li><a href="#">Testimonials</a></li>
            <li><a href="#">Jargon Buster</a></li>
            <li><a href="#">News</a></li>
            <li><a href="#">Contact Us</a></li>
        </ul>
    </div>
    <div class="border-section">
        <div class="bottom">
            <div class="logos-sec">
                <a href="#"><img src="@Url.Content("~/Content/CONTACT_files/logo-1.gif")" alt=""></a>
                <a href="#"><img src="@Url.Content("~/Content/CONTACT_files/logo-2.gif")" alt=""></a>
                <a href="#"><img src="@Url.Content("~/Content/CONTACT_files/logo-3.gif")" alt=""></a>
                <a href="#"><img src="@Url.Content("~/Content/CONTACT_files/logo-4.gif")" alt=""></a>
                <a href="#"><img src="@Url.Content("~/Content/CONTACT_files/logo-5.gif")" alt=""></a>
                <a href="#"><img src="@Url.Content("~/Content/CONTACT_files/logo-6.gif")" alt=""></a>
            </div>
        </div>
    </div>
</div>
}

<h2>Contact us</h2>
<div class="clearfix">
    <div class="section-1">
        <p>Are you considering selling, buying, letting or renting? We offer professional property services designed to meet your needs... Experience the difference, call us now on 020 8558 1147.</p>
        <p>
            46 Church Lane <br>
            Leytonstone, London <br>
            E11 1HE
        </p>
        <dl class="contact-information">
            <dt>Tel:</dt>
            <dd>020 8558 1147</dd>
            <dt>Fax: 	</dt>
            <dd>020 8556 6665</dd>
            <dt>Email:</dt>
            <dd>info@tradingplacesproperty.com</dd>
        </dl>
    </div>
    <div class="section-2">
        <div class="border-sec-1">
            <div class="top">
                <div class="bottom">
                    <div class="map-section" id="map-canvas"></div>
                </div>
            </div>
        </div>
    </div>
</div>

@using (Html.BeginForm("Contact", "RealEstate", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
<div class="border-section-l">
    <div class="top">
        <div class="bottom">
            <div class="form">
                <span class="legend">Mandatory field <span class="required">*</span></span>
                <div class="row clearfix">
                    @Html.ValidationSummary()
                </div>
                <div class="row clearfix">
                    @Html.SpanTitle("Title", "required", "*")
                    
                    <select style="position:absolute;width:200px; height:22px;line-height:20px;margin:0;padding:0;" onchange="document.getElementById('Title').value = this.options[this.selectedIndex].text; document.getElementById('idValue').value = this.options[this.selectedIndex].value;">
                        <option></option>
                        <option value="Recall">Recall</option>
                        <option value="Request">Request</option>
                        <option value="Other">Other</option>
                    </select>
                    <div onfocus="this.select()">
                        @Html.EditorFor(model => model.Title)
                    </div>

                    <input name="idValue" id="idValue" type="hidden">
                    </div>
                <div style="position:relative;width:200px;height:25px;border:0;padding:0;margin:0;">

                </div>
                <div class="row clearfix">
                    @Html.SpanTitle("Name", "required", "*")
                    @Html.EditorFor(model => model.Name)
                </div>
                <div class="row clearfix">
                    @Html.SpanTitle("Phone number", "required", "*")
                    @Html.EditorFor(model => model.PhoneNumber)
                </div>
                <div class="row clearfix">
                    @Html.HiddenFor(model => model.ContactTime)
                    <label for="contact">Best time to contact you</label>
                    <div id="contact" class="contact">
                        <div class="clearfix anytime-item"><label for="#">Anytime</label> <input id='cb1' type="checkbox" onchange='setBestTime("cb1", "Anytime");'></div>
                        <div class="clearfix">
                            <ul class="item  item-1">
                                <li><label for="#">Monday AM</label> <input id='cb2' type="checkbox" onchange='setBestTime("cb2", "Monday AM");'></li>
                                <li><label for="#">Monday PM</label> <input id='cb3' type="checkbox" onchange='setBestTime("cb3", "Monday PM");'></li>
                            </ul>
                            <ul class="item">
                                <li><label for="#">Tuesday AM</label> <input id='cb4' type="checkbox" onchange='setBestTime("cb4", "Tuesday AM");'></li>
                                <li><label for="#">Tuesday PM</label> <input id='cb5' type="checkbox" onchange='setBestTime("cb5", "Tuesday PM");'></li>
                            </ul>
                            <ul class="item">
                                <li><label for="#">Wednesday AM</label> <input id='cb6' type="checkbox" onchange='setBestTime("cb6", "Wednesday AM");'></li>
                                <li><label for="#">Wednesday PM</label> <input id='cb7' type="checkbox" onchange='setBestTime("cb7", "Wednesday PM");'></li>
                            </ul><ul class="item">
                                <li><label for="#">Thursday  AM</label> <input id='cb8' type="checkbox" onchange='setBestTime("cb8", "Thursday  AM");'></li>
                                <li><label for="#">Thursday  PM</label> <input id='cb9' type="checkbox" onchange='setBestTime("cb9", "Thursday  PM");'></li>
                            </ul>
                        </div>
                        <ul class="item item-1 friday-item">
                            <li><label for="#">Friday  AM</label> <input id='cb10' type="checkbox" onchange='setBestTime("cb10", "Friday  AM");'></li>
                            <li><label for="#">Friday  PM</label> <input id='cb11' type="checkbox" onchange='setBestTime("cb11", "Friday  PM");'></li>
                        </ul><ul class="item">
                            <li><label for="#">Saturday  AM</label> <input id='cb12' type="checkbox" onchange='setBestTime("cb12", "Saturday  AM");'></li>
                            <li><label for="#">Saturday  PM</label> <input id='cb13' type="checkbox" onchange='setBestTime("cb13", "Saturday  PM");'></li>
                        </ul>
                    </div>
                </div>
                <div class="row clearfix">
                    @Html.SpanTitle("Message", "required", "*")
                    @Html.TextAreaFor(model => model.Message, 4, 50, null)
                </div>
                <div class="row clearfix">
                    <label for="#">&nbsp;</label>
                    <li><button class="main-btn3" type="submit">Send</button></li>
                </div>
            </div>
        </div>
    </div>
</div>
}

TradingPlaces/Views/RealEstate/Delete.cshtml
@model TradingPlaces.Models.Construction

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this building?</h3>

<div class="main-info-form">
    <fieldset>
        <legend>Building</legend>
        <div class="row clearfix">
            @Html.LabelFor(model => model.Id, "ID")
            @Html.TextBoxFor(model => model.Id, new { disabled = "disabled", @readonly = "readonly" })
            @Html.LabelFor(model => model.Price, "Price £")
            @Html.TextBoxFor(model => model.Price, new { disabled = "disabled", @readonly = "readonly" })
            @Html.LabelFor(model => model.Postcode, "Postcode")
            @Html.TextBoxFor(model => model.Postcode, new { disabled = "disabled", @readonly = "readonly" })
        </div>
        <div class="row clearfix">
            @Html.LabelFor(model => model.Address, "Address")
            <div id="Address">
                @Html.TextBoxFor(model => model.Address, new { disabled = "disabled", @readonly = "readonly" })
            </div>
            @Html.LabelFor(model => model.Area, "Area")
            @Html.TextBoxFor(model => model.Area, new { disabled = "disabled", @readonly = "readonly" })
        </div>
    </fieldset>
</div>

<ul class="buttons-bar clearfix">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <li><a href="#" onclick="history.go(-1); return false;" class="btn2"><span>Cancel</span></a></li>
        <li><button class="btn1" type="submit">Delete</button></li>
    }
</ul>

TradingPlaces/Views/RealEstate/Index.cshtml
@using TradingPlaces.Models
@model IEnumerable<Construction>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@Scripts.Render("~/Scripts/Simple-0.0.1.js")

<style>
    .thumb img {
        border: 2px solid #55c5e9; /* Рамка вокруг фотографии */
        padding: 10px; /* Расстояние от картинки до рамки */
        background: #666; /* Цвет фона */
        margin-right: 10px; /* Отступ справа */
        margin-bottom: 10px; /* Отступ снизу */
    }
</style>

@section MenuCap {
    <ul class="main-nav">
    <li class="active"><a href="/RealEstate/">MAIN</a></li>
    <li><a href="/RealEstate/Sale">SALE</a></li>
    <li><a href="/RealEstate/Info">INFO</a></li>
    <li><a href="/RealEstate/Contact">CONTACT</a></li>
</ul>
}


<div id="img">
    <p class="thumb">
        @{
            foreach (var item in Model)
            {
                string imagePath = "data:image/jpeg;base64," + Convert.ToBase64String(item.Image);
                <a href="/RealEstate/Info/@item.Id"><img class="prev_img" alt="" src=@imagePath height="150" width="200" /></a>
            }
        }
    </p>
</div>

TradingPlaces/Views/RealEstate/Info.cshtml
@model TradingPlaces.Models.Construction
@{
    ViewBag.Title = "Info";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section scripts
{
<script type="text/javascript">
    function del_image() { 
        $('#prev_image').attr('src', '/Content/img/no_image.png');
        $('#Image').val('');
    }
    function preview() {
        filepath = $('#file_image').attr('value');
        if (filepath == "") {
            alert("Please select a file")
        } else {
            var input = $('#file_image')[0];
            var f = input.files[0];
            if (f.type.match('image.*')) {
                var fr = new FileReader();
                fr.onload = function (e) { $("#prev_image").attr("src", fr.result); }
                fr.readAsDataURL(f);
            }
        }
    }
    $('#Price').keypress(function (obj) {
        obj = (obj) ? obj : window.obj
        var charCode = (obj.which) ? obj.which : obj.keyCode
        if (charCode == 44) {
            if ($('#Price').attr('value').search(',') != -1) {
                return false
            }
            else {
                return true
            }
        }
        if (charCode > 31 && (charCode < 48 || charCode > 57)) {
            return false;
        }
        return true;
    });

</script>
}

@section MenuCap {
    <ul class="main-nav">
        <li><a href="/RealEstate/">MAIN</a></li>
        <li><a href="/RealEstate/Sale">SALE</a></li>
        <li class="active"><a href="/RealEstate/Info">INFO</a></li>
        <li><a href="/RealEstate/Contact">CONTACT</a></li>
    </ul>
}

@section SideBar {
    <div class="sidebar">
        <div class="border-section">
            <div class="bottom">
                <h3>Properties Menu</h3>
                <ul class="vert-nav2">
                    <li class="active"><a class="main-btn" href="#"><span>Main Information</span></a></li>
                    <li><a class="main-btn" href="#"><span>Descriptions</span></a></li>
                    <li><a class="main-btn" href="#"><span>Images</span></a></li>
                    <li><a class="main-btn" href="#"><span>2D Plan</span></a></li>
                    <li><a class="main-btn" href="#"><span>3D Plan</span></a></li>
                    <li><a class="main-btn" href="#"><span>EPC</span></a></li>
                </ul>
            </div>
        </div>
    </div>
}

<h2>Main Information</h2>
@using (Html.BeginForm("Info", "RealEstate", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="main-info-form">
        <div class="row clearfix">
            @Html.ValidationSummary()
        </div>
        <div class="row clearfix">
            @Html.LabelFor(model => model.Id, "ID")
            @Html.TextBoxFor(model => model.Id, new { disabled = "disabled", @readonly = "readonly" })
            @Html.LabelFor(model => model.Price, "Price £")
            @Html.EditorFor(model => model.Price)
            @Html.LabelFor(model => model.Postcode, "Postcode")
            @Html.EditorFor(model => model.Postcode)
        </div>

        <div class="row clearfix">
            @Html.LabelFor(model => model.Address, "Address")
            @Html.EditorFor(model => model.Address)
            @Html.LabelFor(model => model.Area, "Area")
            @Html.DropDownListFor(model => model.Area, new SelectList(new string[] { "Area 1", "Area 2", "Area 3", "Area 4" }), "")
        </div>
        <div class="row clearfix">
            @Html.LabelFor(model => model.Tenure, "Tenure")
            @Html.DropDownListFor(model => model.Tenure, new SelectList(new string[] { "Freehold", "Leasehold" }))
        </div>
        <div class="row clearfix">
            @Html.LabelFor(model => model.SSTC, "SSTC")
            @Html.EditorFor(model => model.SSTC)
        </div>
        <div class="row clearfix">
            <div class="col">
                <div class="row">
                    @Html.LabelFor(model => model.Bedrooms, "Bedrooms")
                    @Html.DropDownListFor(model => model.Bedrooms, new SelectList(new int[] { 1, 2, 3, 4, 5 }), 1)
                </div>
                <div class="row">
                    @Html.LabelFor(model => model.Bathrooms, "Bathrooms")
                    @Html.DropDownListFor(model => model.Bathrooms, new SelectList(new int[] { 1, 2, 3, 4, 5 }), 1)
                </div>
                <div class="row">
                    @Html.LabelFor(model => model.Garden, "Garden")
                    @Html.EditorFor(model => model.Garden)
                </div>
            </div>
            <div class="col">
                <div class="row clearfix">
                    @Html.LabelFor(model => model.LivingRooms, "Living rooms")
                    @Html.DropDownListFor(model => model.LivingRooms, new SelectList(new int[] { 1, 2, 3, 4, 5 }), 1)
                </div>
                <div class="row clearfix">
                    @Html.LabelFor(model => model.Shower, "Shower")
                    @Html.EditorFor(model => model.Shower)
                </div>
                <div class="row clearfix">
                    @Html.LabelFor(model => model.Parking, "Parking")
                    @Html.EditorFor(model => model.Parking)
                </div>
            </div>
        </div>
        <div class="row clearfix rel">
            <label for="main-photo">Main Photo</label>
            <div class="editor-field">
                <input id="file_image" type="file" name="uploadImage" />
                <a href="#" onclick="preview()">Preview</a>
            </div>
            <div class="uploaded-img">
                @Html.HiddenFor(model => model.Image)
                <div id="results-img">
                    @{
    if (Model.ImageString != null && Model.ImageString != "")
    {
        @Html.Raw(Model.ImageString)
    }
    else
    {
        <img id="prev_image" src="~/Content/img/no_image.png" />
    }
                    }
                </div>
                <a href="#" onclick="del_image()" class="del">Delete Image</a>
            </div>
        </div>
        <div class="row">
            @Html.LabelFor(model => model.Сomment, "Sale's Corner")
            @Html.TextAreaFor(model => model.Сomment, 4, 50, null)
        </div>
        <div class="row">
            @Html.LabelFor(model => model.PropertyStatus, "Property status")
            @Html.DropDownListFor(model => model.PropertyStatus, new SelectList(new string[] { "Live", "Not live" }))
            <p class="hint">
                Hide a property on your website, PropertySpring, and all data feeds (Rightmove, etc).
                <br>
                N/B/ Changes may take up to 24 hours to take effect on Rightmove.
            </p>
        </div>
    </div>

    <ul class="buttons-bar clearfix">

            <li><a href="#" onclick="history.go(-1); return false;" class="btn2"><span>Cancel</span></a></li>
            <li><button class="btn1" type="submit">Save</button></li>

    </ul>
}

TradingPlaces/Views/RealEstate/Sale.cshtml
@using TradingPlaces.Models
@using TradingPlaces.Helpers
@model IEnumerable<Construction>

@{
    ViewBag.Title = "Sale";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section scripts
{
    <script type="text/javascript">
    $(function(){
        $('#Show').change(function () {
            location.href = '/RealEstate/Sale?pageNum=0&pageSize=' + $('#Show').attr('value')
        })
    })

    </script>
}

@section MenuCap {
    <ul class="main-nav">
        <li><a href="/RealEstate/">MAIN</a></li>
        <li class="active"><a href="/RealEstate/Sale">SALE</a></li>
        <li><a href="/RealEstate/Info">INFO</a></li>
        <li><a href="/RealEstate/Contact">CONTACT</a></li>
    </ul>
}

<h2 class="clearfix"><span class="f-left">List of Real Estate</span>
    <div class="paging f-right">
        @Html.Label("Show ")
        @Html.DropDownList("Show", new SelectList(new int[] { 5, 10, 15, 20, 25 },(int)Html.ViewData["PageSize"]) )
        <span>items per page</span>
    </div>
</h2>

<table cellpadding="0" cellspacing="0" class="global-table">
    <tr>
        <th class="id">ID</th>
        <th class="location">Location</th>
        <th class="postcode">Postcode</th>
        <th class="price">Price</th>
        <th class="bedrooms">Bedrooms</th>
        <th class="livingrooms">Living rooms</th>
        <th class="bathrooms">Bathrooms</th>
        <th class="shower">Shower</th>
        <th class="garden">Garden</th>
        <th class="parking">Parking</th>
    </tr>
    @{
        string oddclass = "odd";
        foreach (var item in Model)
        {
            <tr class="@oddclass">

                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Address)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Postcode)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Price)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Bedrooms)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LivingRooms)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Bathrooms)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Shower)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Garden)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Parking)
                </td>
                <td>
                    <div class="rel">
                        <ul class="salebtns">
                            <li class="edit">@Html.ActionLink("edit", "Info", new { Id = @item.Id, pageNum = ViewData["PageNum"] }) </li>
                            <li class="delete"><a href="/RealEstate/Delete/@item.Id">delete</a></li>
                        </ul>
                    </div>
                </td>
            </tr>
            if (oddclass == "")
            {
                oddclass = "odd";
            }
            else
            {
                oddclass = "";
            }
        }}

</table>
<div class="nav-bottom clearfix">
    <a href="/RealEstate/Info/" class="btn-add"><span>Add New Item</span></a>  

    <ul class="paging-numeral f-right">
        @Html.PagingNavigator((int)Html.ViewData["PageNum"], (int)Html.ViewData["PageSize"], (int)Html.ViewData["ItemsCount"])
    </ul>

</div>

TradingPlaces/Views/RealEstate/SendEmail.cshtml
@{
    ViewBag.Title = "SendEmail";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section scripts
{
    <script type="text/javascript">
        $(document).ready(function() {
            var t = setTimeout("redirect()", 3000);
        })
        function redirect() 
        { 
            location.href = '/RealEstate/Sale/';
        }
    </script>
}

<h2>@ViewBag.Message</h2>